    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress-service
      annotations:
        nginx.ingress.kubernetes.io/use-regex: 'true'
        nginx.ingress.kubernetes.io/rewrite-target: /$1
    spec:
      ingressClassName: nginx
      rules:
        - http:
            paths:
              - path: /?(.*)
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: frontend-go-clusterip
                    port:
                      number: 3000
              - path: /api/?(.*)
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: backend-go-clusterip
                    port:
                      number: 8080